spring:
  cloud:
    azure:
      servicebus:
        connection-string: <>
    stream:
      bindings:
        consume-in-0:
          destination: <>
          contentType: application/azure-message
          consumer:
            checkpoint-mode: MANUAL
            sessionsEnabled: false
        supply-out-0:
          destination: <>
          contentType: application/azure-message
      servicebus:
        queue:
          bindings:
            consume-in-0:
              producer:
                partitionKeyExpression: payload.sessionId
      function:
        definition: consume;supply;
      poller:
        fixed-delay: 1000
        initial-delay: 0